InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI

.drone.yml
=> ECR moved to global layer

.drone.yml
=> it shouldn't checkout branch - was only for test

.drone.yml
Add AWS Secrets manager integration to drone yaml file
=> Add secrets integration for drone

.dockerignore, .drone.yml, build_utils/check_build_number.sh
Add build utils for awaiting ECS rollout
=> Add build utils

config/initializers/filter_parameter_logging.rb
Hide confirmation code from log file
=> [NT] Hide confirmation code from log file

app/views/devise/sessions/new.html.haml, app/views/upload/data_rules.html.haml, config/locales/devise.en.yml, features/sign_in.feature
Those changes required in [VCCS-557](https://eaflood.atlassian.net/browse/VCCS-557), slide 5 and 7
=> [NT] Fix invalid email error message

app/views/passwords/confirm_reset.html.haml
=> [NT] Fix reset password error message

app/services/cognito/confirm_forgot_password.rb
[JIRA](https://eaflood.atlassian.net/browse/NTR-449)
=> [NTR-449] Reset password shows invalid error message

.drone.yml, jmeter/ntr_valid_upload.jmx
added a while loop condition to make sure the script stops if it encounters a problem.
=> added while loop condition

app/api_wrappers/register_checker_api.rb, app/controllers/passwords_controller.rb, app/helpers/application_helper.rb, app/services/base_service.rb, app/services/cognito/auth_user.rb, app/services/cognito/cognito_base_service.rb, app/services/cognito/confirm_forgot_password.rb, app/services/cognito/forgot_password.rb, app/services/cognito/get_user.rb, app/services/cognito/respond_to_auth_challenge.rb, app/services/csv_upload_service.rb, app/views/errors/internal_server_error.html.haml, app/views/errors/not_found.html.haml, app/views/passwords/reset.html.haml, config/initializers/remote_authenticatable.rb, config/locales/en.yml, features/step_definitions/helper_steps.rb, features/step_definitions/password_reset_steps.rb, features/step_definitions/sign_in_steps.rb, spec/requests/passwords/change_spec.rb, spec/requests/sign_in_spec.rb, spec/services/cognito/auth_user_spec.rb, spec/services/cognito/forgot_password_spec.rb, spec/services/cognito/get_user_spec.rb, spec/services/cognito/respond_to_auth_spec.rb, spec/services/csv_upload_service_spec.rb
[JIRA](https://eaflood.atlassian.net/browse/NTR-459)
=> [NTR-459] Add logging to Cognito calls

Gemfile
http://drone-1506943830.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web/34/1/10
=> [NT] Fix SDOC

app/models/application_record.rb, app/models/base_form.rb, app/models/confirm_reset_password_form.rb, app/models/new_password_form.rb, app/models/reset_password_form.rb, app/models/user.rb
=> [NTR-463] Add models documentation

app/api_wrappers/base_api.rb, app/api_wrappers/register_checker_api.rb
[JIRA](https://eaflood.atlassian.net/browse/NTR-464)
Document API wrapper
=> [NTR-464] Add api wrapper documentation

app/mailers/application_mailer.rb, app/services/base_service.rb, app/services/csv_upload_service.rb, app/services/email_validator.rb, app/services/example_csv.rb, app/views/devise/sessions/new.html.haml, config/application.rb, config/initializers/env_variables_checker.rb
[JIRA](https://eaflood.atlassian.net/browse/NTR-467)
I also moved `SES_FROM_EMAIL` variable to app.rb because we use it for all project configuration. I think it's a good idea to hold all settings in one place.
=> Features/ntr 467/add docs to services

config/initializers/filter_parameter_logging.rb
details in: 
https://github.com/aws/aws-sdk-ruby/issues/2122
=> [NT] Fix Cognito param filter

app/controllers/application_controller.rb, app/controllers/cookies_controller.rb, app/controllers/errors_controller.rb, app/controllers/passwords_controller.rb, app/controllers/upload_controller.rb
[JIRA](https://eaflood.atlassian.net/browse/NTR-465)
=> [NTR-465] Add controller documentation

.drone.yml
=> Added UI to BS build

.drone.yml, jmeter/ntr_valid_upload.jmx, pa11y/.pa11yci.conf.js, pa11y/Dockerfile, pa11y/Makefile
=> added pa11y

app/views/layouts/_cookies_banner.haml, app/views/layouts/_navbar.haml
[JIRA](https://eaflood.atlassian.net/browse/NTR-523)
=> [NTR-523] Add id to url

.drone.yml
moved pa11y tests after await rollout
=> moved pa11y tests

.drone.yml
=> Associate with JAQU-CAZ-IAC feature branch

jmeter/ntr_valid_upload.jmx
=> increased duration of upload processing to 5 seconds

.drone.yml
=> add codedeploy step

.drone.yml
Updates the Drone pipeline by adding in new SIT steps on release branch creation
=> Update drone pipeline for SIT

app/views/upload/index.html.haml, features/sign_in.feature
=> [NT] Change main page content

app/views/cookies/index.html.haml, features/cookies.feature
=> [NT] Rename cookies header

.drone.yml
Updates Drone file to use more explicit when clauses and adds a terraform plan step for SIT and higher
=> Drone file updates

.drone.yml
Add terraform workspace fallbacks
=> Add terraform workspace creation fallbacks

config/initializers/session_store.rb
=> [NT] Add secure flag to session

app/javascript/packs/application.js, app/views/layouts/_google_analytics.html.erb, app/views/layouts/application.html.haml, config/initializers/content_security_policy.rb
=> [NTR-358] Add nonse

app/javascript/src/cookiesBanner/init.js, app/javascript/styles/application.scss, app/views/layouts/_cookies_banner.haml, config/initializers/content_security_policy.rb
I moved inline styling to a dedicated class
=> [NTR-358] Move cookie banner styling to class

config/initializers/content_security_policy.rb
Not sure about it, but maybe it will fix something
=> [NTR-358] Change default CSP to 'none'

.drone.yml
=> Test zap in drone

app/helpers/application_helper.rb, app/mailers/application_mailer.rb, app/mailers/upload_mailer.rb, app/views/devise/sessions/new.html.haml, app/views/upload_mailer/success_upload.html.haml
https://eaflood.atlassian.net/browse/NTR-555
As in task
=> [NTR-555] Change success upload email copy

app/views/layouts/_google_analytics.html.erb
https://eaflood.atlassian.net/browse/NTR-547
=> [NTR-547] Add GA anonymization

public/robots.txt
https://eaflood.atlassian.net/browse/NTR-548
I added blocking every bot for all the content as described here - https://www.robotstxt.org/faq/prevent.html
=> [NTR-548] Add robots.txt

app/javascript/src/cookiesBanner/styles.scss, app/views/static_pages/accessibility.html.haml, app/views/static_pages/cookies.html.haml, app/views/static_pages/privacy_policy.html.haml
Bug appears only on production
=> [NT] Fix draft label on production

app/views/static_pages/cookies.html.haml
[JIRA](https://eaflood.atlassian.net/browse/NTR-565)
Fix link name on cookies page
=> [NTR-565] Fix link name on cookies page

pa11y/.pa11yci.conf.js, pa11y/Makefile
Update pa11y scripts to include data rules page and upload success page.
=> Update pa11y tests to include data rules page and upload success page

pa11y/.pa11yci.conf.js
Add new static pages to pa11y for NTR UI
=> Add new static pages to pa11y

app/views/layouts/_cookies_banner.haml, app/views/layouts/_footer.html.haml, app/views/static_pages/privacy_policy.html.haml, config/routes.rb, features/static_pages.feature, spec/requests/static_pages_spec.rb
Remove accessibility link from footer
=> [NT] Remove accessibility link from footer

.drone.yml
Add shared secret for ruby application to better facilitate zero-downtime deployments
=> Add shared secret key base from secrets manager

app/views/layouts/_footer.html.haml, app/views/static_pages/privacy_policy.html.haml, features/static_pages.feature, features/step_definitions/static_pages_steps.rb
[JIRA](https://eaflood.atlassian.net/browse/NTR-583)
=> [NTR-583] Update content for privacy policy

app/views/static_pages/cookies.html.haml
[JIRA](https://eaflood.atlassian.net/browse/NTR-585)
=> [NTR-585] Remove draft badge from cookie page

app/views/static_pages/privacy_policy.html.haml
[JIRA](https://eaflood.atlassian.net/browse/NTR-583)
I forgot to remove the badge label from privacy page
=> [NTR-583] Remove draft badge from privacy page

.drone.yml, pa11y/.pa11yci.conf.js
=> fixed urls

app/views/static_pages/privacy_policy.html.haml
[JIRA](https://eaflood.atlassian.net/browse/NTR-583)
Fix bug and update links design on policy page
=> [NTR-583] Update the links design on privacy policy page

config/initializers/content_security_policy.rb
=> [NT] Add data to font in CSP

app/views/static_pages/privacy_policy.html.haml
**TPDPB-17**(I don't have access to jira project so no link atm)
=> [TPDPB-17] Update privacy policy text

.rubocop.yml, config/environments/production.rb
https://eaflood.atlassian.net/browse/TPDPB-5
Added some custom headers for production ENV.
=> [TPDPB-5] Add security headers

.drone.yml, jmeter/ntr_valid_upload.jmx
=> fixed drone and updated jmeter script

.drone.yml, .github/PULL_REQUEST_TEMPLATE, .rubocop.yml, .scss-lint.yml, Gemfile, Gemfile.lock, README.md, app/javascript/src/cookiesBanner/styles.scss, app/javascript/styles/application.scss, config/environments/production.rb, features/step_definitions/upload_steps.rb, package.json, spec/requests/upload/index_spec.rb, yarn.lock
[JIRA](https://eaflood.atlassian.net/browse/CAZ-1477)
=> [CAZ-1477] Migrate from govuk-lint

app/javascript/packs/application.js
=> [NT] Refactor app.js

app/views/upload/data_rules.html.haml
[JIRA](https://eaflood.atlassian.net/browse/TPDPB-16)
=> [TPDPB-16] Update data rules content

.drone.yml
Drone file updates for ECS deployments
=> Drone file corrections for ECS

app/views/static_pages/accessibility.html.haml, app/views/static_pages/cookies.html.haml, app/views/static_pages/privacy_notice.html.haml
=> [NT] Add back button to static pages

.drone.yml
=> Ammended SIT end to end test browsers

package.json, yarn.lock
=> [NT] Update package.json

.drone.yml
=> R1.0.4 - Updated correct branches for sit and preprod environments

.drone.yml, package.json, yarn.lock
https://github.com/sass/node-sass/issues/2816
Used this package to add exclude: https://www.npmjs.com/package/improved-yarn-audit
=> [NT] Add improved-yarn-audit

app/views/static_pages/accessibility_statement.html.haml
[JIRA](https://eaflood.atlassian.net/browse/CAZB-342)
=> [CAZB-342] Update accessibility statement page

.drone.yml, Gemfile.lock, app/views/static_pages/privacy_notice.html.haml, yarn.lock
=> [CAZB-106] Update privacy notice page and drone.yml

app/views/static_pages/privacy_notice.html.haml
=> [NT] Fix typo on privacy notice page

app/views/static_pages/privacy_notice.html.haml, yarn.lock
=> [CAZB-106] Add links to privacy notice page

app/views/static_pages/privacy_notice.html.haml, yarn.lock
=> [CAZB-106]. fix broken build

app/views/static_pages/accessibility_statement.html.haml
=> [CAZB-362] Update accessibility page

app/views/devise/sessions/new.html.haml, app/views/static_pages/privacy_notice.html.haml, pa11y/.pa11yci.conf.js
=> [NT] Fix pa11y tests

app/services/cognito/auth_user.rb, app/services/cognito/confirm_forgot_password.rb, app/services/cognito/forgot_password.rb, app/services/cognito/get_user.rb, app/services/cognito/respond_to_auth_challenge.rb, app/services/email_validator.rb, spec/requests/sign_in_spec.rb, spec/services/cognito/auth_user_spec.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZB-350)
=> [CAZB-350] Modify usernames are in lower case to use in Cognito

.drone.yml
Add drone steps for new ST environment
=> [CI SKIP] Add ST steps for drone pipeline

Gemfile, Gemfile.lock, app/services/csv_upload_service.rb, app/views/upload/data_rules.html.haml, package.json, yarn.lock
=> [CAZB-449] Revert data rules page changes and add csv content type to uploaded file

.drone.yml, app/views/static_pages/accessibility_statement.html.haml
=> Promote v1.2.0 to staging

app/views/static_pages/cookies.html.haml, app/views/static_pages/cookies/_table_head.html.haml
[JIRA](https://eaflood.atlassian.net/browse/CAZB-585)
=> [CAZB-585] Update cookies page

pa11y/.pa11yci.conf.js
=> [NT] Refactor pa11y test

app/views/layouts/_cookie_control.html.erb
=> [CAZB-640] `Accept all cookies` button enabled GA cookies by default

.drone.yml
=> fixed ntr tests

app/views/layouts/_cookie_control.html.erb
[JIRA](https://eaflood.atlassian.net/browse/CAZB-741)
=> [CAZB-741] Hide Control Cookie buttons and add `Save and close` button

.drone.yml
=> removed end to end tests

pa11y/.pa11yci.conf.js
=> added waits

.drone.yml, app/models/search_vrn_form.rb, config/locales/en.yml, features/vehicles/search_vrn.feature, spec/models/search_vrn_form_spec.rb
[JIRA](https://eaflood.atlassian.net/browse/CAZB-730?focusedCommentId=198590&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198590)
Change error message and add year validation, e.g. `-2020` now not a valid year
=> [CAZB-730] Add year validation and change error message

.rubocop.yml, app/api_wrappers/vehicles_checker_api.rb, app/controllers/vehicles_controller.rb, app/javascript/styles/application.scss, app/models/historical_vrn_details.rb, app/models/paginated_vrn_history.rb, app/models/vrn_history.rb, app/views/vehicles/_pagination.html.haml, app/views/vehicles/_pagination_button.html.haml, app/views/vehicles/historic_search.html.haml, config/routes.rb, features/step_definitions/vehicles/search_vrn_steps.rb, features/support/env.rb, features/support/session_helper.rb, features/vehicles/search_vrn.feature, package.json, spec/api_wrappers/vehicles_checker_api/licence_info_historical_spec.rb, spec/fixtures/files/responses/licence_info_historical_response.json, spec/models/historical_vrn_details_spec.rb, spec/models/paginated_vrn_history_spec.rb, spec/models/vrn_history_spec.rb, spec/requests/vehicles/historic_search_spec.rb, spec/requests/vehicles/submit_search_spec.rb, spec/support/mock_helper.rb, yarn.lock
[JIRA](https://eaflood.atlassian.net/browse/CAZB-731)
--------------------------------------------
=> [CAZB-731] Display VRN audit logs

Gemfile, Gemfile.lock, app/api_wrappers/vehicles_checker_api.rb, app/controllers/vehicles_controller.rb, app/models/historical_vrn_details.rb, app/models/search_vrn_form.rb, app/models/vrn_history.rb, spec/api_wrappers/vehicles_checker_api/licence_info_historical_spec.rb, spec/fixtures/files/responses/licence_info_historical_response.json, spec/models/historical_vrn_details_spec.rb, spec/models/search_vrn_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-731
=> [CAZB-731] Add dates to query and remove mocked response for historical search

app/models/vrn_history.rb, spec/models/vrn_history_spec.rb
https://eaflood.atlassian.net/browse/CAZB-731
=> [CAZB-731] Change action value `Created` to `Added`

app/views/vehicles/historic_search.html.haml, features/step_definitions/helper_steps.rb, features/step_definitions/vehicles/search_vrn_steps.rb, features/vehicles/search_vrn.feature
https://eaflood.atlassian.net/browse/CAZB-731
=> [CAZV-731] Hide the table headers when no historical data found

app/javascript/styles/application.scss, spec/models/search_vrn_form_spec.rb
=> Remove unused a css class

app/api_wrappers/aws_credentials_api.rb, config/initializers/amazon_s3.rb, spec/api_wrappers/aws_credentials_api_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-1076
The first part of the card. 
Created API wrapper to get AWS credentials for Task. 
Used it to log returned details. 
We will check the logs when it is live.
=> [CAZB-1076] Add API wrapper to get AWS credentials

app/api_wrappers/aws_credentials_api.rb, app/controllers/upload_controller.rb, config/initializers/amazon_s3.rb
Changed the place we log the result to be able to validate the response.
=> [CAZB-1076] Change the place we log retuned data

.drone2.yml
=> CAZB-872 drone changes for web layer aws restructure- jaqu-lower environment

.drone2.yml
=> updated source terraform-iac correct path

.drone2.yml
=> corrected deployments dir path

.drone2.yml
=> added sonar block

.drone2.yml
=> updated deployment layer workspace

.drone2.yml
=> ECR issue fix

.drone2.yml
=> Feature/cazb 872/ntr web drone changes

.drone2.yml
=> updated lambda bucket name

app/views/layouts/_navbar.haml
=> Remove search header link

app/views/layouts/_navbar.haml
This reverts commit 5fee1f929c2dfac2cde8ee5829ec157d690bd958.
=> Revert "remove search header link (#290)"

.drone2.yml
=> updated drone file in align with IAC changes

.drone2.yml
=> updated drone file with tf env path

app/javascript/styles/cookie_control.scss, app/views/layouts/_cookie_control.html.erb, app/views/layouts/application.html.haml
https://eaflood.atlassian.net/browse/CAZB-1031
=> [CAZB-1031] Update CookieControl to version 9

.drone.yml, app/views/layouts/application.html.haml, package.json, yarn.lock
=> Add the SRI hash to Cookie Control

app/views/layouts/application.html.haml
https://eaflood.atlassian.net/browse/CAZB-1507
=> [CAZB-1508] Update check sum for cookie controller

app/models/search_vrn_form.rb, spec/models/search_vrn_form_spec.rb
https://eaflood.atlassian.net/browse/CAZB-1596
=> [CAZB-1596] Unable to Search Historic results for a specific date 

.drone2.yml
=> updated drone file with account name

.drone2.yml
=> Updated ntr-web drone changes for controlled env

.drone2.yml
=> Updated st env branch

.drone2.yml
=> updated jaqu_contolled service account for ecr

Dockerfile.build, Dockerfile.test, config/initializers/amazon_s3.rb, config/initializers/aws_ses.rb
=> Refactor AWS env vars in Dockerfile

Dockerfile.build
=> correct file path

.drone2.yml
=> Updated sit changes

.drone2.yml
=> Updated drone changes for preprod environment

.drone2.yml
=> Updated ecs rollout step for preprod

Gemfile.lock, app/helpers/application_helper.rb, config/application.rb
=> Feat/cazsm 51,52,53/defra email change to informed

app/helpers/application_helper.rb, config/application.rb
This reverts commit 13090392a7d20cee6555ab32694428d759adf21d.
=> Revert "Change mail address to TaxiPHVDatabase.Support@informed.com"

.drone2.yml
=> updated preprod drone pipelines and pinned versions

.env.example, app/views/layouts/_gtm_noscript.html.erb, app/views/layouts/_gtm_script.html.erb, app/views/layouts/application.html.haml, config/initializers/content_security_policy.rb
https://eaflood.atlassian.net/browse/CAZB-1631
=> [CAZB-1631] Added GTM scripts

.drone2.yml
=> updated prod drone changes

.drone2.yml
=> Updated drone pipeline for prod env

.drone2.yml
=> Updated preprod/prod ecs rollout step

.drone2.yml
Update pre-prod in new AWS environment
=> Update pre-prod in new AWS environment

.env.example, app/views/layouts/_gtm_noscript.html.erb, app/views/layouts/_gtm_script.html.erb, app/views/layouts/application.html.haml, config/initializers/content_security_policy.rb
=> Promote develop to ST v2.3.0

.drone2.yml
=> removed aws service credentials for preprod and prod environments

.env.example
=> Remove example values from `env.example` file

app/controllers/sessions_controller.rb, app/views/devise/sessions/new.html.haml, config/locales/en.yml, config/routes.rb, features/password_reset.feature, features/sign_in.feature, features/step_definitions/force_password_change_steps.rb, features/upload.feature, spec/requests/sign_in_spec.rb
https://eaflood.atlassian.net/browse/CAZB-1907
=> [CAZB-1907] Error message changes

config/locales/devise.en.yml, features/sign_in.feature
https://eaflood.atlassian.net/browse/CAZB-1935
=> [CAZB-1935] Sign in error message

.drone2.yml
=> UAT drone deployment steps

app/services/cognito/forgot_password/confirm.rb
https://eaflood.atlassian.net/browse/CAZB-1932
=> [CAZB-1932] Show correct message when user email not exist

app/helpers/application_helper.rb, app/models/new_password_form.rb, app/services/cognito/respond_to_auth_challenge.rb, app/views/passwords/new.html.haml, config/locales/en.yml, features/step_definitions/force_password_change_steps.rb, spec/models/new_password_form_spec.rb
Jira card: https://eaflood.atlassian.net/browse/CAZB-1943
Used the same NewPasswordForm as CS UI. 
Updated tests and views.
=> [CAZB-1943] Set up new password error messages

.drone.yml
=> remove .env.example steps from drone pipeline

app/services/cognito/forgot_password/confirm.rb, config/initializers/aws_custom_logger.rb, config/initializers/filter_parameter_logging.rb
https://eaflood.atlassian.net/browse/CAZB-2091
Removed `Aws::CognitoIdentityProvider::Client` logging
Added `username` to list of filtered parameters
=> [CAZB-2091] Fix "confirmation_code" leak in logs

app/views/layouts/_navbar.haml
Remove search link from navigation bar
=> Remove search link from navigation bar

.drone2.yml
=> Update new pre-prod to v2.2.1

app/views/layouts/_navbar.haml
Update new Production with v2.2.1
=> Update new Production with v2.2.1

.drone2.yml
=> updated drone2 file to be merged into develop branch

app/views/static_pages/accessibility_statement.html.haml, app/views/vehicles/_date_range.html.haml, app/views/vehicles/search.html.haml, config/locales/en.yml, features/step_definitions/vehicles/search_vrn_steps.rb, features/vehicles/search_vrn.feature
https://eaflood.atlassian.net/browse/CAZB-2081
=> [CAZB-2081] NTR Search Page content

app/views/vehicles/historic_search.html.haml
https://eaflood.atlassian.net/browse/CAZB-2083
=> [CAZB-2083] Historical Search content updates

app/models/vrn_details.rb, spec/api_wrappers/vehicles_checker_api/licence_info_spec.rb, spec/fixtures/files/responses/licence_info_response.json, spec/models/vrn_details_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2082
=> [CAZB-2082] Quick search results content updates

.drone2.yml
Domain switch for dev cutover in drone 2 file
=> Domain switch for dev cutover in drone 2 file

pa11y/Dockerfile
=> Add gnupg2 to pa11y deps

pa11y/Dockerfile
=> Update gnupg package in pa11y

.drone2.yml
=> updated IAC branches

.drone2.yml
=> filx dev and st environment URLs

app/views/vehicles/_date_range.html.haml
=> [CAZB-2081] Update start date help text

.drone2.yml
=> updated prod url

app/services/back_link_history_service.rb, features/step_definitions/vehicles/search_vrn_steps.rb, features/vehicles/search_vrn.feature, spec/services/back_link_history_service_spec.rb
Same fix as for current PR: https://github.com/InformedSolutions/JAQU-CAZ-Fleets-UI/pull/432
=> Fix back button history when page was refreshed

pa11y/.pa11yci.conf.js, pa11y/Dockerfile, pa11y/Makefile
=> Try to fix accessibility tests

.drone2.yml, .env.example, Dockerfile.test, app/controllers/application_controller.rb, app/services/cognito/cognito_base_service.rb, app/services/cognito/forgot_password/confirm.rb, app/services/cognito/forgot_password/rate_limit_verification.rb, app/services/cognito/forgot_password/reset.rb, app/services/cognito/forgot_password/update_user.rb, app/services/csv_upload_service.rb, config/application.rb, config/initializers/amazon_s3.rb, config/initializers/aws_ses.rb, features/step_definitions/upload_steps.rb, features/upload.feature, sonar-project.properties, spec/services/csv_upload_service_spec.rb
https://eaflood.atlassian.net/browse/CAZB-2332
=> [CAZB-2332] Add CSV upload size limit

.drone.yml, .drone2.yml
https://eaflood.atlassian.net/browse/CAZB-2660
Updated env variable.
=> [CAZB-2660] Survey Link Update - Qualtrics (Production)

app/views/passwords/confirm_reset.html.haml, app/views/passwords/new.html.haml, config/locales/en.yml
https://eaflood.atlassian.net/browse/CAZB-2326
=> [CAZB-2326] Update password policy

.env.example, app/controllers/passwords_controller.rb, app/services/cognito/auth_user.rb, app/services/cognito/cognito_base_service.rb, app/services/cognito/lockout/attempt_user_unlock.rb, app/services/cognito/lockout/is_user_locked.rb, app/services/cognito/lockout/update_user.rb, app/services/cognito/lockout/user_data.rb, app/services/cognito/lockout/verify_invalid_logins.rb, features/account_lockout.feature, features/step_definitions/account_lockout_steps.rb, spec/requests/passwords/change_spec.rb, spec/services/cognito/lockout/attempt_user_unlock_spec.rb, spec/services/cognito/lockout/is_user_locked_spec.rb, spec/services/cognito/lockout/update_user_spec.rb, spec/services/cognito/lockout/user_data_spec.rb, spec/services/cognito/lockout/verify_invalid_logins_spec.rb
Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-2781
Added account lockout mechanism same as [here](https://github.com/InformedSolutions/JAQU-CAZ-MOD-UI/pull/205)
N/A
=> [CAZB-2781] Account lockout

app/services/cognito/auth_user.rb, app/services/cognito/lockout/verify_invalid_logins.rb
=> [CAZB-2781] Reload user data when checking account lockout

pa11y/.pa11yci.conf.js
=> password change

app/javascript/styles/application.scss, app/views/vehicles/search.html.haml
https://eaflood.atlassian.net/browse/CAZB-3038
Added styles and message content
=> [CAZB-3038] Search purpose message

app/javascript/styles/application.scss, app/views/vehicles/search.html.haml
=> Update RC with develop

Gemfile, Gemfile.lock
=> Bump rails

Gemfile, Gemfile.lock, config/locales/en.yml, spec/i18n_spec.rb
Removed unused keys and added test. Also sorted keys by `i18n-tasks normalize` command, needed for test passing.
=> Add `i18n-tasks` gem and test for it

.gitignore, app/services/cognito/get_user.rb, app/services/cognito/update_preferred_username.rb, config/application.rb, spec/services/cognito/update_preferred_usrname_spec.rb
https://eaflood.atlassian.net/browse/CAZB-3416
=> [CAZB-3416] Update `preferred_username` on Cognito

config/locales/en.yml, spec/models/search_vrn_form_spec.rb
=> [CAZB-3520] Start date error message fix

Gemfile.lock, yarn.lock
=> Cazsm 88/application dependancy patching ntr UI

app/views/vehicles/_date_range.html.haml
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4122
Updated browser validations for date fields.
=> [CAZB-4122] Align historical search dates validation with CSP

Gemfile.lock, app/controllers/application_controller.rb, app/exceptions/referer_xss_exception.rb, app/services/security/referer_xss_handler.rb, spec/services/security/referer_xss_handler_spec.rb
https://eaflood.atlassian.net/browse/CAZB-4674
=> [CAZB-4674] Back link XSS vulnerability prevention

.drone2.yml
=> [CAZB-4674] Deployment fix

app/controllers/application_controller.rb, app/exceptions/invalid_host_exception.rb, app/services/security/host_header_validator.rb, config/application.rb, spec/services/security/host_header_validator_spec.rb
Jira Card: https://eaflood.atlassian.net/browse/CAZB-4649
=> [CAZB-4649] Add host validation for every request

app/controllers/application_controller.rb, app/javascript/packs/application.js, app/javascript/src/backLink/init.js, app/views/errors/service_unavailable.html.haml, app/views/shared/_js_back_link.html.haml
* When the user was redirected to Service Unavailable page, the back link was rendered and it was initialized with the referrer value. 
* In order to prevent the issue the back link was altered with JS-back link on the Service Unavailable page
=> [CAZB-4674] Change back link on Service Unavailable page

app/controllers/sessions_controller.rb, app/forms/username_and_password.rb, app/views/devise/sessions/new.html.haml, config/environments/production.rb, config/i18n-tasks.yml, config/locales/en.yml, spec/forms/username_and_password_spec.rb, spec/requests/sign_in_controller_spec.rb
* https://eaflood.atlassian.net/browse/CAZB-4667
=> [CAZB-4667] Username enumeration through header fix

app/controllers/sessions_controller.rb, app/forms/username_and_password.rb, app/views/devise/sessions/new.html.haml, config/environments/production.rb, config/i18n-tasks.yml, config/locales/en.yml, spec/forms/username_and_password_spec.rb, spec/requests/sign_in_controller_spec.rb
=> [CAZB-4667] Username enumeration through header fix (#602)

app/controllers/application_controller.rb, app/services/security/host_header_validator.rb, spec/services/security/host_header_validator_spec.rb
=> [CAZB-4858] Allow multiple hosts

.drone2.yml, .iyarc, yarn.lock
Security tests: http://drone-1587293244.eu-west-2.elb.amazonaws.com/InformedSolutions/JAQU-CAZ-National-Taxi-Register-UI/1091
=> Bump yarn libs to fix Security tests

.drone2.yml
[CAZB-4710] Lower domain migration
=> [CAZB-4710] Lower domain migration

.drone2.yml, app/controllers/application_controller.rb
=> Draft release candidate/v2.12.0

Gemfile.lock
=> Bump addressable to v2.8.0
